### GET request to example server
GET http://localhost:8080/api/v1/software-engineers/2

### GET request to example server
GET http://localhost:8080/api/v1/software-engineers

###

POST http://localhost:8080/api/v1/software-engineers
Content-Type: application/json

{
  "name": "Dary",
  "techStack": ["html/css","React.js"]
}

###
POST http://localhost:8080/api/v1/software-engineers
Content-Type: application/json

{
"name": "Casper",
"techStack": ["html","React.js"]
}

###
POST http://localhost:8080/api/v1/software-engineers
Content-Type: application/json

{
"name": "Joe",
"techStack": ["ts","React.js","js/ts"]
}


###
GET http://localhost:8080/api/v1/software-engineers/name/Casper

###
GET http://localhost:8080/api/v1/software-engineers/techStack/html,
    React.js

###
DELETE http://localhost:8080/api/v1/software-engineers/3